markdown: kramdown
highlighter: false
plugins: ./_plugins
paginate: 10
safe: false

#站点基础配置
title: i CCM
subTitle: Always Curious.
description: 
url: http://iccm.cc
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /index.html
    icon: icon-home
    class: home
  - text: 文章归档
    url: /archives.html
    icon: icon-reorder
    class: none
  - text: Linkedin
    url: http://cn.linkedin.com/in/chaominchen
    icon: icon-linkedin
    class: none
  - text: Github
    url: https://github.com/ccmien
    icon: icon-github
    class: none

  # - text: 关于我
  #   url: /contact.html
  #   icon: icon-envelope-alt
  #   class: none
  # - text: 联系我
  #   url: http://www.zhanxin.info/contact.html
  #   icon: icon-heart
  #   class: none
  # - text: 博客源代码
  #   url: https://github.com/pizn/iLotus
  #   icon: icon-github
  #   class: none

page:
  - text: 归档
    url: /archives.html
    last: true
  # - text: 喜欢的网站
  #   url: /links.html
  #   last: true
  - text: Linkedin
    url: http://cn.linkedin.com/in/chaominchen
    icon: icon-linkedin
    class: none
  - text: Github
    url: https://github.com/ccmien
    icon: icon-github
    class: none
#评论信息
disqus:
  config: false
  id: m
duoshuo:
  config: true
  id: iccm

author:
  name: CCM
